#!/bin/bash
#
# Run a test for TIMEOUT seconds inside virtme-ng and catch potential errors.

# Maximum time the test run.
TEST_TIMEOUT=30

# Maximum timeout for the guest run (this is used to hard-shutdown the guest in
# case of system hangs).
GUEST_TIMEOUT=60

# Test command to run
TEST_CMD="uname -r"

# Check if virtme-ng is available.
if [ ! -x `which vng` ]; then
    echo "vng not found, please install virtme-ng to enable testing"
    exit 1
fi

# NOTE: virtme-ng automatically runs the kernel from the current working
# directory by default.
#
rm -f /tmp/output
(timeout --foreground --preserve-status ${GUEST_TIMEOUT} \
    vng --force-9p --disable-microvm --verbose -- \
        "timeout --foreground --preserve-status ${TEST_TIMEOUT} ${TEST_CMD}" \
            2>&1 </dev/null || true) | tee /tmp/output
grep -v " Speculative Return Stack Overflow" /tmp/output | \
        sed -n -e '/\bBUG:/q1' \
            -e '/\bWARNING:/q1'
res=$?
if [ ${res} -ne 0 ]; then
    echo "FAIL"
    exit 1
else
    echo "OK"
fi
